version: "3.5"

services:

  ingredient-database:
    image: postgres:10
    container_name: Group-service-database
    hostname: Group-database
    networks:
     - backend-network
    environment:
      POSTGRES_USER: Group
      POSTGRES_PASSWORD: gp
      POSTGRES_DB: gp
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ingredient", "-d", "Group"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - pgdata-Groups:/var/lib/postgresql/data
      
    restart: on-failure
    stdin_open: true
    tty: true

  ingredient-service:
    container_name: Group-service    
    image:  MMM/Group_service:latest
    hostname: ingredient-service
    environment:
      THORNTAIL_KAFKA_DASH_CONFIGURATION_HOST: "kafka"
      THORNTAIL_KAFKA_DASH_CONFIGURATION_PORT: "9092"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_GroupS_CONNECTION_DASH_URL: "jdbc:postgresql://Group-database:5432/Groups"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_GroupS_DRIVER_DASH_NAME: 'postgresql'   
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_GroupS_USER_DASH_NAME: 'Groups'
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_GroupS_PASSWORD: 'gp'
    networks:
      - backend-network   
    ports:
      - "10080:28080"
    depends_on:
       - Group-database
volumes:
   pgdata-Groups:

  

networks:
    backend-network:
      external:
        name: backend-network
