version: "3.5"

services:

  #Zookeeper service provides distributed configuration management to Kafka
  zookeeper:
    image: zookeeper:3.4.9
    container_name: zookeeper 
    hostname: zookeeper
    networks:
      - backend-network
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ./target/zk-single-kafka-single/zoo1/data:/data
      - ./target/zk-single-kafka-single/zoo1/datalog:/datalog

#   kafka is the messaging backbone of the micro-service architecture. The objective is avoid point 2 point connections.
  kafka:
    image: confluentinc/cp-kafka:5.3.3
    container_name: kafka 
    hostname: kafka
    networks:
      - backend-network    
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - ./target/zk-single-kafka-single/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  profile-database:
    image: postgres:10
    container_name: profile-database
    hostname: profile-database
    networks:
     - backend-network
    environment:
      POSTGRES_USER: pro
      POSTGRES_PASSWORD: pro
      POSTGRES_DB: pro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pro", "-d", "pro"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - pgdata-profile:/var/lib/postgresql/data
      - ./test-data/profile.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    stdin_open: true
    tty: true

  #The counterparty service provides counterparty data, it is also the single version of truth for these data
  profile-service:
    container_name: profile-service  
    image: diges/profile-service:latest
    hostname: profile-service
    environment:
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_PROFILE_CONNECTION_DASH_URL: "jdbc:postgresql://profile-database:5432/profile"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_PROFILE_DRIVER_DASH_NAME: 'postgresql'   
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_PROFILE_USER_DASH_NAME: 'pro'
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_PROFILE_PASSWORD: 'pro'
      THORNTAIL_KAFKA_DASH_CONFIGURATION_HOST: "kafka"
      THORNTAIL_KAFKA_DASH_CONFIGURATION_PORT: "9092"
    networks:
      - backend-network 
    ports:
      - "12085:28080"
    depends_on:
       - kafka
#################################################################################################
#												#
#################################################################################################


  group-database:
    image: postgres:10
    container_name: group-database
    hostname: group-database
    networks:
     - backend-network
    environment:
      POSTGRES_USER: gro
      POSTGRES_PASSWORD: gro
      POSTGRES_DB: ing
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "gro", "-d", "gro"]
      interval: 30s
      timeout: 30s
      retries: 3
    volumes:
      - pgdata-group:/var/lib/postgresql/data
      - ./test-data/group.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure
    stdin_open: true
    tty: true

  #The counterparty service provides counterparty data, it is also the single version of truth for these data
  group-service:
    container_name: group-service  
    image: diges/group-service:latest
    hostname: group-service
    environment:
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_GROUP_CONNECTION_DASH_URL: "jdbc:postgresql://group-database:5432/group"
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_GROUP_DRIVER_DASH_NAME: 'postgresql'   
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_GROUP_USER_DASH_NAME: 'gro'
      THORNTAIL_DATASOURCES_DATA_DASH_SOURCES_GROUP_PASSWORD: 'gro'
      THORNTAIL_KAFKA_DASH_CONFIGURATION_HOST: "kafka"
      THORNTAIL_KAFKA_DASH_CONFIGURATION_PORT: "9092"
    networks:
      - backend-network 
    ports:
      - "12084:28080"
    depends_on:
       - kafka
       
       
volumes:
  pgdata-profile:
  pgdata-group:



networks:
  backend-network:
    driver: bridge

