# This is a basic workflow to help you get started with Actions


name: Docker Series Builds

on: [push]


jobs:
  build:     
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: download node
        run: nvm install $NODE_VERSION
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin 

     #- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: echo ok
        run: echo "ok"
      - name: change directory
        run: cd docker_building_scripts
      - name: run building docker services
        run: sudo sh build_services.sh
      - name: Test
        run: cd .. && ./mvnw clean test


