# This is a basic workflow to help you get started with Actions
# helped with login : https://stackoverflow.com/questions/58226756/how-to-login-to-docker-registries-using-github-actions

name: Docker Series Builds

on: [push]


jobs:
  build:     
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - uses: actions/checkout@v2
      #- name: docker logout ??
      #  run: docker logout
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USER }}" --password-stdin
      #- name: Login to Docker.io
      #  run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.io -u "${{ secrets.DOCKER_USER }}" --password-stdin
      #- name: Login to GitHub Container Registry
      #  uses: docker/login-action@v1
      #  with:
      #    registry: ghcr.io
      #    #username: ${{ github.repository_owner }}
      #    #password: ${{ secrets.GITHUB_TOKEN }}
      #    username: ${{ secrets.DOCKER_USER }}
      #    password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          edin0: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
     #- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: echo ok
        run: echo "ok"
      - name: docker build images
        run: |
          # build les images a partir du dockerfile
          sudo docker image build -t service_film_build -f ./services/test_film/Dockerfile .
      - name: docker tag images
        run: |
         # change les noms des images et les envoies au docker hub
         sudo docker tag service_film_build docker.io/edin0/service_film_build
      - name: docker push tagged images
        run: |
         echo ${{ secrets.TEST_PASSWORD }} | docker login -u ${{ secrets.TEST_USER }} --password-stdin
         echo ${{ secrets.TEST_PASSWORD }} | docker login docker.io -u ${{ secrets.TEST_USER }} --password-stdin

         # push images tagged
         sudo docker push docker.io/edin0/service_film_build
      - name: docker test the build
        run: |
         # test the build
         sudo docker run -p 8080:8080 -d edin0/service_film_build
      - name: docker test
        run: |
         #check website
         sudo curl localhost:8080
      - name: Test
        run: cd .. && ./mvnw clean test


