# This is a basic workflow to help you get started with Actions


name: Docker Series Builds

on: [push]


jobs:
  build:     
    runs-on: ubuntu-latest
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u "${{ secrets.DOCKER_USER }}" --password-stdin
     #- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: echo ok
        run: echo "ok"
      #- name: change directory
      #  run: cd docker_building_scripts
      #- name: run building docker services
      #  run: sudo sh build_services.sh
      - name: docker build images
        run: |
          # build les images a partir du dockerfile
          sudo docker image build -t service_film_build -f ../services/test_film/Dockerfile .
      - name: docker tag images
        run: |
         # change les noms des images et les envoies au docker hub
         sudo docker tag service_film_build edin0/service_film_build:latest
      - name: docker push tagged images
        run: |
         # push images tagged
         sudo docker push edin0/service_film_build:latest
      - name: docker test the build
        run: |
         # test the build
         sudo docker run -p 8080:8080 -d edin0/service_film_build
      - name: docker test
        run: |
         #check website
         sudo curl localhost:8080
      - name: Test
        run: cd .. && ./mvnw clean test


